### ISSUE TITLE
package.json is missing thunkify-wrap

### ISSUE THREAD

**Issue by j03m** [lambtron/medium-cli#3]
sup, started using the cli today. First publish went like this:

```
jmordetsky@Josephs-MacBook-Pro ~/A/p/j03m-medium> medium publish
module.js:338
    throw err;
    ^

Error: Cannot find module 'thunkify-wrap'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/medium-cli/lib/publish/articles.js:7:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
jmordetsky@Josephs-MacBook-Pro ~/A/p/j03m-medium> npm install thunkify-wrap -g
thunkify-wrap@1.0.4 /usr/local/lib/node_modules/thunkify-wrap
└── enable@1.3.2
jmordetsky@Josephs-MacBook-Pro ~/A/p/j03m-medium> medium publish
jmordetsky@Josephs-MacBook-Pro ~/A/p/j03m-medium> 
```

Looks like you need to add thunkify-wrap to package.json?

**Comment by lambtron** [comment]
ah shoot, thank you. wonder how that slipped by everyone else!
